#include etiquette

function onLoad()
  params = {
    click_function = "setupTraits",
    function_owner = self,
    label          = "Setup",
    position       = {0, 1, 0},
    rotation       = {0, 180, 0},
    width          = 800,
    height         = 400,
    font_size      = 340,
    color          = {0.5, 0.5, 0.5},
    font_color     = {1, 1, 1},
    tooltip        = "Setup Persuasion for all seated players!",
  }
  self.createButton(params)
end